force-app/main/default/objects/child_product__c/child_product__c.object-meta.xml
<CustomObject>
    <label>child product</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>child product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>child products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/child_product__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>child products (Parent Product)</relationshipLabel>
    <relationshipName>child_products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/child_product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>child products</relationshipLabel>
    <relationshipName>child_products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunitylineitemHandlerclass.cls
public class OpportunitylineitemHandlerclass
{
    public static boolean flag=true;
   Public static void afterInsert(List<OpportunityLineItem> LineList, Map<Id, OpportunityLineItem> newMap)
    {
        if(flag){
            flag=false;
        set<Id> parentproductids = new set<Id>();
        set<id> childprodIds = new set<Id>();
        set<id> pricebookIds=new set<id>();
        Map<Id,Set<Id>> productIdToChildProductIds = new Map<Id,Set<Id>>();
        //List<OpportunityLineItem> linelist=(List<OpportunityLineItem>)newList;
        //Map<Id,OpportunityLineItem> oppLineItemsMap=new Map<Id,OpportunityLineItem>(linelist);
        for(OpportunityLineItem opp:linelist)
        {
            parentproductids.add(opp.product2Id);
            pricebookIds.add(opp.opportunity.pricebook2Id);
            System.debug('pricebookIds=='+ pricebookIds);
            System.debug('parentproductids=='+parentproductids);
        }
        
        if(parentproductids.size()>0){
            for(child_product__c cids:[SELECT Product__c,Parent_Product__c FROM child_product__c WHERE Parent_Product__c IN:parentproductids])
            {
                childprodIds.add(cids.Product__c);
               
                if(productIdToChildProductIds.containsKey(cids.Parent_Product__c))
                {
                    productIdToChildProductIds.get(cids.Parent_Product__c).add(cids.Product__c);
                    system.debug('productIdToChildProductIds  get:'+ productIdToChildProductIds);
                }
                else
                {
                    productIdToChildProductIds.put(cids.Parent_Product__c, new set<Id>{cids.Product__c});
                    system.debug('productIdToChildProductIds else='+ productIdToChildProductIds);
                }
            }
        }
        List<OpportunityLineItem> childOpportunityLineItems = new List<OpportunityLineItem>();
        for(OpportunityLineItem lineItem :linelist)
        {
           
            if(productIdToChildProductIds.containsKey(lineItem.Product2Id))
            {
               
                for(Id childProductId : productIdToChildProductIds.get(lineItem.Product2Id))
                {
                    system.debug('childProductId=='+ childProductId);
                    OpportunityLineItem childItem = new OpportunityLineItem();
                    childItem.Product2Id = childProductId;
                    childItem.OpportunityId = lineItem.OpportunityId;
                    childItem.Quantity = lineItem.Quantity;
                    childItem.UnitPrice = 0;
                    childItem.PricebookEntryId = lineItem.PricebookEntryId;
                    childOpportunityLineItems.add(childItem);
                   
                }
            }
        }
       
        if(!childOpportunityLineItems.isEmpty())
        {
            try
            {
                INSERT childOpportunityLineItems;
                system.debug('childOpportunityLineItems=='+childOpportunityLineItems);
            }
            catch(Exception error)
            {
                System.debug('Error::'+error.getMessage());
            }
        }
        }
    }
}