force-app/main/default/objects/child_product__c/child_product__c.object-meta.xml
<CustomObject>
    <label>child product</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>child product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>child products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/child_product__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>child products (Parent Product)</relationshipLabel>
    <relationshipName>child_products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/child_product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>child products</relationshipLabel>
    <relationshipName>child_products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTriggerHandler_Test.cls
@istest(SeeAllData=true)
private class OpportunityLineItemTriggerHandler_Test {
    
    @istest
     static void TestMethodAfterinsert(){
        list<Opportunity> oppList = new list<Opportunity>{new Opportunity(Name = 'Test 1', StageName='Prospecting',CloseDate = system.today()),
            new Opportunity(Name = 'test 2', StageName ='Prospecting',CloseDate = system.today())};
                INSERT oppList;
     
            
        
        Pricebook2 pb22 = new Pricebook2(Name='testDIE');
        insert pb22;
        
            list<Product2> pro2List = new list<Product2>{new Product2(Name='laptop', isActive=true),
                new Product2(Name='Laptopbag', isActive=true)};
        insert pro2List;
            for(Product2 prodRec : pro2List){
            child_product__c chldProd = new child_product__c(Parent_Product__c = pro2List[0].Id, Product__c=pro2List[1].Id );
        PricebookEntry pbe2 =new PricebookEntry(Product2Id=pro2List[0].Id,Pricebook2Id=Test.getStandardPricebookId(),UnitPrice=1
                                                );
        insert pbe2;
        
        OpportunityLineItem OPplineitem2 = new OpportunityLineItem (Quantity=2, OpportunityId=oppList[0].Id,UnitPrice=1,PriceBookEntryId=pbe2.Id);
        insert OPplineitem2;
                list<opportunity> Optylist = [SELECT id, (SELECT id FROM OpportunityLineItems) FROM opportunity WHERE Id In:oppList];
         system.assertEquals(2, Optylist.size());
        }
        
    }
}