force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>It is used for MAXFIT app
To store error log files</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ErrorLog-{0}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <description>Store the Date &amp; Time details when the Error Occurred</description>
    <inlineHelpText>Store the Date &amp; Time details when the Error Occurred</inlineHelpText>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Stores the Complete Stack Track about the Problem</description>
    <inlineHelpText>Stores the Complete Stack Track about the Problem</inlineHelpText>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogTriggerhandler.cls
public class ErrorLogTriggerhandler {
    public static void getdetails(list<string> ProcessName, list<string> LogDetails, list<Datetime> LogDateTime){
        list<Error_Log__c> ErrorLogList = new list<Error_Log__c>();
        for(integer i=1;i <=LogDetails.size(); i++){
            Error_Log__c  Errorlog = new Error_Log__c();
            Errorlog.Process_Name__c = ProcessName[i];
            Errorlog.Log_Details__c = LogDetails[i];
            Errorlog.Log_Date_Time__c = LogDateTime[i];
            ErrorLogList.add(Errorlog);
        }
        INSERT ErrorLogList;
    }
}