force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendees</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendees__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Enter Phone number</description>
    <inlineHelpText>(+91)-(1234567789)</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object is created for MAX FIT app</description>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Enter Event Name</description>
    <inlineHelpText>Please Enter Event Name</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Enter event start date and time</description>
    <inlineHelpText>Please Enter event start date and time</inlineHelpText>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0}</displayFormat>
        <label>Attendee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <description>MDR with Attendee</description>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This is in MDR with Event object</description>
    <inlineHelpText>Please enter a value from Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Event_Organizer__c is created for MAX FIT app</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Enter a email to connect</description>
    <inlineHelpText>Enter a valid email
Email format should be in abc@gmail.com</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Event Organizers</relationshipLabel>
    <relationshipName>Event_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number to connect</description>
    <inlineHelpText>Enter number in valid format
(+91)-(1236547896)</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>This object is created for Event Management ( MAX FIT )
 app given by onesh sir</description>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>S No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>AndorrA</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/Landmark__c.field-meta.xml
<CustomField>
    <fullName>Landmark__c</fullName>
    <label>Landmark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventAttendeeTriggerHandler.cls
public class EventAttendeeTriggerHandler {
    public static void SendEmail(Map<Id,Event_Attendee__c> newEventAttendeeMap){ 
        Set<Id> eventIdSet=new Set<Id>(); 
        Map<Id,Event__c> eventIdToLocation=new Map<Id,Event__c>(); 
        list<messaging.Email> messageEmailList = new list<messaging.Email>();
        for(Event_Attendee__c eventAttendeeRec : newEventAttendeeMap.values()){ 
            eventIdSet.add(eventAttendeeRec.Event__c); 
        } 
        for(Event__c eventRecords: [SELECT Id,Start_Date_Time__c,End_Date_Time__c,
                                    Location__r.City__c,Location__r.Country__c, Location__r.Landmark__c,
                                    Location__r.Postal_Code__c, Location__r.State__c,Location__r.Street__c,
                                    Organizer__r.name FROM Event__c WHERE Id IN : eventIdSet]){
                                        eventIdToLocation.put(eventRecords.Id,eventRecords); 
                                    }
        if(eventIdToLocation.size()> 0){
            for(Event_Attendee__c EvantAttendeRec : [SELECT id,Attendees__r.Name,Attendees__r.Email__c,Attendees__r.Phone__c,Event__r.Name__c,Event__r.Start_Date_Time__c,Event__r.End_Date_Time__c FROM Event_Attendee__c WHERE Id IN:newEventAttendeeMap.keyset()]){
                messaging.SingleEmailMessage message = new messaging.SingleEmailMessage();
                list<string> tooAddressList = new List<string>{EvantAttendeRec.Attendees__r.Email__c};
                    message.setToAddresses(tooAddressList);
                message.setSubject('Pass for the'+' '+ EvantAttendeRec.Event__r.Name__c);
                string body = ' Dear'+ ' '+EvantAttendeRec.Attendees__r.Name +',<br/>';
                body= body+'Thank you for registering for'+ ' '+ EvantAttendeRec.Event__r.Name__c+' <br> which will be Organized on ' +EvantAttendeRec.Event__r.Start_Date_Time__c+'& will be held in <br>'+ eventIdToLocation.get(EvantAttendeRec.Event__c).Location__r.Street__c+',';
                body= body+ eventIdToLocation.get(EvantAttendeRec.Event__c).Location__r.Country__c +',<br>';
                body= body+ eventIdToLocation.get(EvantAttendeRec.Event__c).Location__r.Landmark__c +',<br>';
                body = body+eventIdToLocation.get(EvantAttendeRec.Event__c).Location__r.State__c +',<br>';
                body = body+eventIdToLocation.get(EvantAttendeRec.Event__c).Location__r.City__c +',<br>';
                body = body+eventIdToLocation.get(EvantAttendeRec.Event__c).Location__r.Postal_Code__c +'.<br>';
                body = body+'We are excited to have you, see you in the event.<br>';
                body = body+'Thanks,<br><br>'+eventIdToLocation.get(EvantAttendeRec.Event__c).Organizer__r.name;
                message.setHtmlBody(body);
                messageEmailList.add(message);
            }
            try{
                messaging.sendemail(messageEmailList);
            }catch(exception e){
                system.debug('error='+ e.getdmlmessage(0));       
            }
        }
    }
}