force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/Resource_Allocation__c.object-meta.xml
<CustomObject>
    <label>Resource Allocation</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/fields/Avg_Weekly_Hours__c.field-meta.xml
<CustomField>
    <fullName>Avg_Weekly_Hours__c</fullName>
    <label>Avg Weekly Hours</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/end_date__c.field-meta.xml
<CustomField>
    <fullName>end_date__c</fullName>
    <label>end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resource Allocations</relationshipLabel>
    <relationshipName>Resource_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/start_date__c.field-meta.xml
<CustomField>
    <fullName>start_date__c</fullName>
    <label>start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Utilization__c/Utilization__c.object-meta.xml
<CustomObject>
    <label>Utilization</label>
    <nameField>
        <label>Utilization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Utilization__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>May</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utilization__c/fields/Monthly_Hou__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Hou__c</fullName>
    <label>Monthly Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Utilization__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Utilizations</relationshipLabel>
    <relationshipName>Utilizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/resourceAllocationTriggerHandler.cls
public class resourceAllocationTriggerHandler {
	public static void createRecord(List<Resource_Allocation__c> newList){
        set<id> resourceAllocationIdSet = new set<id>();
        list<utilization__c> utilizationList = new  list<utilization__c>();
        for(Resource_Allocation__c rec : newList){
            resourceAllocationIdSet.add(rec.id);
        }
        if(resourceAllocationIdSet.size() > 0){
            for(Resource_Allocation__c resAllocRec : [SELECT id,name,Resource__c,start_date__c,end_date__c,Avg_Weekly_Hours__c FROM Resource_Allocation__c WHERE ID IN :resourceAllocationIdSet]){
                utilization__c util = new utilization__c();
                 integer noofmonths = resAllocRec.end_date__c.monthsBetween(resAllocRec.start_date__c);
        integer startmonth=resAllocRec.Start_Date__c.month();
        integer endmonth =resAllocRec.End_Date__c.month();
        Integer noOfDays = resAllocRec.Start_Date__c.daysBetween(resAllocRec.End_Date__c);
        System.debug('no of months--->'+noofmonths);
        System.debug('start date---months=='+resAllocRec.Start_Date__c.month());
        System.debug('End date---months=='+resAllocRec.end_date__c.month());
        system.debug('days between in a month=='+noOfDays);
                for(integer i=startmonth;i<=endmonth;i++){
                     util.Month__c = String.valueOf(i);
                      util.Name = resAllocRec.Resource__c+ String.valueOf(i);
               
                util.Monthly_Hou__c = resAllocRec.Avg_Weekly_Hours__c * 4;
                util.Resource__c = resAllocRec.Resource__c;
              
                utilizationList.add(util);
                }
            }
        }
        if(utilizationList.size() > 0){
            UPSERT utilizationList;
        }
        
    }
}