force-app/main/default/objects/Mobile__c/Mobile__c.object-meta.xml
<CustomObject>
    <label>Mobile</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mobile__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mobile__c/fields/Discount_Status__c.field-meta.xml
<CustomField>
    <fullName>Discount_Status__c</fullName>
    <label>Discount Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MobileShopeeClass.cls
public class MobileShopeeClass {
    Public static void NewCustomerDiscount(list<mobile__c> MobileList1){
        for(Mobile__c m:MobileList1 ){
            if(m.brand__c == 'Samsung'){
                m.Price__c = m.price__c - (m.price__c *10)/100;
				m.Discount_Status__c = 'You have got 10% discount';
            }else if(m.brand__c == 'Apple'){
                 m.Price__c = m.price__c - (m.price__c *20)/100;
				m.Discount_Status__c = 'You have got 20% discount';
            }
        }
    }

    Public static void OldCustomerDiscount(list<mobile__c> MobileList2){
        for(Mobile__c m:MobileList2 ){
            if(m.brand__c == 'Samsung'){
                m.Price__c = m.price__c - (m.price__c *5)/100;
				m.Discount_Status__c = 'You have got 5% discount';
            }else if(m.brand__c == 'Apple'){
				m.Discount_Status__c = 'Sorry no discount as of now';
            }
        }
    }
}