force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object is created for MAX FIT app</description>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Max number of seats</description>
    <inlineHelpText>It shows max number of seats for Event object</inlineHelpText>
    <label>Max Seats</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Enter Event Name</description>
    <inlineHelpText>Please Enter Event Name</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Enter event start date and time</description>
    <inlineHelpText>Please Enter event start date and time</inlineHelpText>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EventDeleteBatchClassTest.cls
@istest
public class EventDeleteBatchClassTest {
    
	@istest
    public static void eventDeleteTestMethod(){
        date Startd=date.Today().addDays(-100);
    date endd=date.Today().addDays(-65);  
        Event__c evant = new Event__c();
        evant.Name__c = 'Test event';
evant.Start_Date_Time__c=datetime.newInstance(Startd.year(), Startd.month(),Startd.day());
evant.End_Date_Time__c=datetime.newInstance(endd.year(), endd.month(),endd.day());
        evant.Max_Seats__c = 500;
        Insert evant;
        Test.startTest();
        
        EventDeleteBatchSchedule.execute(NULL);
    /*  ContactBdayEmailBatchClass BatchClass = new ContactBdayEmailBatchClass();
        DataBase.executeBatch(BatchClass);*/
     Test.stopTest();
    }
}