force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object is created for MAX FIT app</description>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Max number of seats</description>
    <inlineHelpText>It shows max number of seats for Event object</inlineHelpText>
    <label>Max Seats</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Enter event start date and time</description>
    <inlineHelpText>Please Enter event start date and time</inlineHelpText>
    <label>Start Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventSpeakers__c/EventSpeakers__c.object-meta.xml
<CustomObject>
    <description>EventSpeakers is the object created for MAX FIT App</description>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Event Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventSpeakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventSpeakers__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This is in Master-Detail  Relationship with Event</description>
    <inlineHelpText>Please Select a value from Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EventSpeakers__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>This is in Master-Detail  relationship  with Speaker</description>
    <inlineHelpText>Please select a value from speaker</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerTriggerHandlerTest.cls
@isTest
public class EventSpeakerTriggerHandlerTest {
    @istest
    public static void DuplicateTest(){
        Speaker__c Speakar = new Speaker__c();
        Speakar.Name = 'Test speaker';
        Speakar.Phone__c = '7894578632';
        INSERT Speakar;
        Event__c evant = new Event__c();
        evant.Start_Date_Time__c = system.today();
  
        evant.Max_Seats__c = 100;
        INSERT evant;
        EventSpeakers__c ES1 = new EventSpeakers__c();
        ES1.Event__c = evant.Id;
        ES1.Speaker__c = Speakar.id;
        INSERT ES1;
        EventSpeakers__c ES2 = new EventSpeakers__c();
        ES2.Event__c = evant.Id;
        ES2.Speaker__c = Speakar.id;
        try{
            Test.startTest();
        INSERT ES2;
            system.assertEquals('For a Speaker there will be only one event at a time', 'For a Speaker there will be only one event at a time');
            Test.stopTest();
        }catch(exception e){
            system.debug('error='+ e.getdmlMessage(0));
        }
    }

}