force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object is created for MAX FIT app</description>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EventSpeakers__c/EventSpeakers__c.object-meta.xml
<CustomObject>
    <description>EventSpeakers is the object created for MAX FIT App</description>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Event Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventSpeakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventSpeakers__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This is in Master-Detail  Relationship with Event</description>
    <inlineHelpText>Please Select a value from Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EventSpeakers__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>This is in Master-Detail  relationship  with Speaker</description>
    <inlineHelpText>Please select a value from speaker</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerTriggerHandler.cls
public class EventSpeakerTriggerHandler {
    public static void rejectDuplicate(list<EventSpeakers__c> newEventSpeakersList){
        set<id> EventIdSet = new set<id>();
        set<id> SpeakerIdSet = new set<id>();
        map<id,EventSpeakers__c> EventSpeakerMap = new map<id,EventSpeakers__c>();
        for(EventSpeakers__c EveSpekr : newEventSpeakersList){
            EventIdSet.add(EveSpekr.Event__c);
            SpeakerIdSet.add(EveSpekr.Speaker__c);
        }
        if(EventIdSet.size() > 0){
            for(EventSpeakers__c  EveSpekrRec : [SELECT id,Name,Speaker__c,Event__c FROM EventSpeakers__c WHERE Event__c IN : EventIdSet AND Speaker__c IN : SpeakerIdSet]){
                EventSpeakerMap.put(EveSpekrRec.Speaker__c, EveSpekrRec);
            }
            if(EventSpeakerMap.size() >0){
                for(EventSpeakers__c EventSpeakerRecord : newEventSpeakersList){
                    if(EventSpeakerMap.get(EventSpeakerRecord.Speaker__c).Event__c == EventSpeakerRecord.Event__c ){
                        EventSpeakerRecord.addError('For a Speaker there will be only one event at a time');
                    }
                }
            }
        }
    }
}